apiVersion: v1
kind: Service
metadata:
  name: nats
  labels:
    name: nats
  namespace: nats
spec:
  type: NodePort
  selector:
    app: nats
  ports:
    - protocol: TCP
      port: 4222
      targetPort: 4222
      nodePort: 30042
      name: client
    - protocol: TCP
      port: 8222
      targetPort: 8222
      nodePort: 30082
      name: http
    - protocol: TCP
      port: 6222
      targetPort: 6222
      nodePort: 30062
      name: "clustering"
